trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Run_App_Service_Deploy_Script
    timeoutInMinutes: 30
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'cccis-jlindsey-sandbox(ff95cccd-cbb7-41a2-b4ba-41917218c03c)'
        ScriptType: 'InlineScript'
        Inline: 'New-AzResourceGroupDeployment -ResourceGroupName $(ResourceGroupName) -Name main -TemplateFile $(System.DefaultWorkingDirectory)/bicep/main.bicep -resourceBaseName $(ResourceBaseName) -location "$(Location)" -vnetName $(VnetName) -administratorLogin $(DBAdminName) -administratorLoginPassword $(DBPassword)' 
    - task: AzureCLI@2
      displayName: Deploy App Service and Partially Configure
      inputs:
        azureSubscription: 'cccis-jlindsey-sandbox(ff95cccd-cbb7-41a2-b4ba-41917218c03c)'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(System.DefaultWorkingDirectory)/deployandConfigAppService.ps1'
        arguments: '-ResourceBaseName $(ResourceBaseName) -ResourceGroupName $(ResourceGroupName) -Location "$(Location)" -DBAdminName $(DBAdminName) -DBPassword $(DBPassword) -VnetName $(VnetName) -SubnetName $(SubnetName) -UseDockerCompose $false'
        workingDirectory: '$(System.DefaultWorkingDirectory)'